#!/usr/bin/env bash

## VARIABLES
THIS_DIR=$(cd "$(dirname "$0")"; pwd)
TDCLI='https://valtman.name/files/telegram-cli-1222'

## Print Colorful
# Print text in red
prtred() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
# Print text in green
prtgrn() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
# Print text in brown
prtbrown() {
  printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}
# update data to the last version
update() {
  git fetch --all && git reset --hard origin/persian && git pull origin persian && chmod +x bot
    prtgrn "
  Bot's source successfully updated
"
}
# Create a new Bot
create() {
  name=bot
  if [[ -e $name.lua ]] ; then
      i=1
      while [[ -e $name-$i.lua ]] ; do
          let i++
      done
      name=$name-$i
  fi
  cat bot.lua >> "$name".lua
  sed -i 's/BOT-ID/'$i'/g' "$name".lua
    prtgrn "Bot "$i" Created."
prtred "Enter: 
       ./bot "$i"
	  
"
}
# Create a new Bot manually
createmanual() {
   prtgrn 'Enter Favourite Bot Number'
  read -rp ' ' ID
    if [[ -e bot-"$ID".lua ]] ; then
      prtred 'There is a bot with this number'
      exit
    else
      if [[ "$ID" =~ ^[0-9]+$ ]] ; then
        cat bot.lua >> bot-"$ID".lua
        sed -i 's/BOT-ID/'$ID'/g' bot-"$ID".lua
        prtgrn "Bot "$ID" Created."
        prtred "Enter: 
             ./bot "$ID"
      "
      else
        prtred "Enter the bot number
    "
        exit
      fi
    fi
}
# Reset data to the last update
fix() {
  git reset --hard FETCH_HEAD
  prtgrn 'Database Reseted and Fixed.'
}
# autolauncher
autolaunch() {
  while true ; do
    for tablighgar in bot-*.lua ; do
      tab="${tablighgar%.*}"
      ltab="${tab/-/ }"
      tmux kill-session -t $tab
      for tg in ~/.telegram-cli/$tab/data/* ; do
        rm -rf $tg/*
      done
      TMUX= tmux new-session -d -s $tab "./$ltab"
      tmux detach -s $tab
    done
    echo -e "Bots are Running..."
    sleep 1200
  done 
}
# clear a bot
clear() {
  sudo service redis-server start
  prtgrn 'Enter Bot Number :'
  read -rp ' ' ID
  rm -rf ~/.telegram-cli/bot-"$ID"/data
  rm -rf bot-"$ID".lua
  redis-cli --raw keys "bot"$ID* | xargs redis-cli del
  prtgrn 'Bot '$ID' Seccessfuly Deleted.'
  exit
}
# install Bot
install() {
  prtgrn 'install Essentials ? (Y/N):'
  read -rp ' ' install
  case "$install" in
    Y|y|بله)
      prtgrn "Downloading telegram-cli..."
      wget "$TDCLI" -O telegram-cli
      chmod +x telegram-cli
      prtgrn "Updating old packages..."
      sudo apt-get -y update && sudo apt-get -y upgrade 
      prtgrn "Installing Essentials packages..."
      sudo apt-get --force-yes install git wget screen tmux libconfig9 libevent-dev libjansson4 libstdc++6 lua-socket lua5.2 liblua5.2 make unzip redis-server software-properties-common g++
      sudo apt-get -y update && sudo apt-get -y upgrade
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y gcc-4.9 g++-4.9 && sudo update-alternatives —install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 —slave /usr/bin/g++ g++ /usr/bin/g++-4.9
      prtgrn "Updating packages..."
      sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt-get -y autoremove
      prtgrn "Restarting redis service..."
      sudo service redis-server restart
      prtgrn 'Fetching latest Bot source code...'
      git pull
      prtgrn 'Essentials of Tablighgar Bot successfully installed!'
      printf 'Create Bot: ./bot create \n'
    ;;
    N|n|خیر)
      prtbrown 'Canceling the operation'
    ;;
    *)
      prtred 'Wrong command'
      install
    ;;
  esac
}
# How to use this script
usage() {
printf "\e[1;36m"
  cat "
    Options:
	  install           Install of Bot
      create            Create a new Bot
      NUMBER            Start bot whit this ID number
      aNUMBER           Start bot whit this ID number in anticrash mod
      createmanual      Create a new Bot manually
      autolaunch        Launch all bots every 20 mins
      update            Update bot source code
      help              Print this message
      fix               Reseting data
"
printf "%s\n\e[0;39;49m"
}
## MAIN ------------------------------------------------------------------------
# Make sure this script run inside Bot directory
cd "$THIS_DIR" || exit
case $1 in
  update)
    update
  ;;
  create)
    create
  ;;
  install)
    install
  ;;
  fix)
    fix
  ;;
  autolaunch)
    autolaunch
  ;;
  help)
    usage
  ;;
  createmanual)
    createmanual
  ;;
  a*)
    id="${1/a/}"
    if [ -a "$THIS_DIR"/bot-"$id".lua ]; then
      screen -x -s bot-"$id" quit
      while true ; do
        screen -s bot-"$id" ./telegram-cli -p bot-"$id" -s bot-"$id".lua
        sleep 10
      done
    else
      usage
    fi
  ;;
  clr)
    clear
  ;;
  *)
    if [ -a "$THIS_DIR"/bot-"$1".lua ]; then
      ./telegram-cli -p bot-"$1" -s bot-"$1".lua
    else
    usage
    fi
  ;;
esac
